services:
  localstack:
    container_name: btg_pactual_localstack
    image: localstack/localstack:latest
    ports:
      - "4567:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,sts
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack:Z"
      - "./scripts/init-dynamodb.sh:/etc/localstack/init/ready.d/init-dynamodb.sh:Z"
      - "/var/run/podman/podman.sock:/var/run/docker.sock:Z"